title: "SCP:CB Multiplayer"
# Uncomment for development.
# theme: "just-the-docs"
remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/logo-602x150.png"
color_scheme: dark

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/scpcbmp/wiki" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Permalink Categories, followed by their titles.
permalink: /:categories/:title